// Newest list goes first: the app opens on the first tab.
// The on-screen keyboard has only A-Z, so every `eng` must be a single word of capital letters.
export const WEEKS = [
  {
    // Book p.14, dictation on Sun 2026-10-11
    label: 'הכתבה 1',
    words: [
      { eng: 'COMPLETE', heb: 'להשלים' },
      { eng: 'MATCH', heb: 'להתאים' },
      { eng: 'CHOOSE', heb: 'לבחור' },
      { eng: 'CORRECT', heb: 'לתקן / נכון' },
      { eng: 'SHARE', heb: 'לשתף / לחלוק' },
      { eng: 'ADD', heb: 'להוסיף' },
      { eng: 'COMPARE', heb: 'להשוות' },
      { eng: 'MEANING', heb: 'משמעות / פירוש' },
      { eng: 'PRACTICE', heb: 'לתרגל / תרגול' },
      { eng: 'SPELL', heb: 'לאיית' },
    ],
  },
  {
    label: 'שבוע 1',
    words: [
      { eng: 'FORGET', heb: 'לשכוח' },
      { eng: 'EVERYONE', heb: 'כולם' },
      { eng: 'FIRST', heb: 'ראשון' },
      { eng: 'SECOND', heb: 'שני' },
      { eng: 'THIRD', heb: 'שלישי' },
      { eng: 'GIVE', heb: 'לתת' },
      { eng: 'HEALTHY', heb: 'בריא' },
      { eng: 'INSTRUCTIONS', heb: 'הוראות' },
      { eng: 'MEAN', heb: 'להתכוון / משמעות' },
      { eng: 'TRY', heb: 'לנסות' },
    ],
  },
  {
    label: 'שבוע 2',
    words: [
      { eng: 'FORGET', heb: 'לשכוח' },
      { eng: 'EVERYONE', heb: 'כולם' },
      { eng: 'FIRST', heb: 'ראשון' },
      { eng: 'SECOND', heb: 'שני' },
      { eng: 'THIRD', heb: 'שלישי' },
      { eng: 'GIVE', heb: 'לתת' },
      { eng: 'HEALTHY', heb: 'בריא' },
      { eng: 'INSTRUCTIONS', heb: 'הוראות' },
      { eng: 'MEAN', heb: 'להתכוון / משמעות' },
      { eng: 'TRY', heb: 'לנסות' },
    ],
  },
  {
    label: 'שבוע 3',
    words: [
      { eng: 'SELDOM', heb: 'לעיתים רחוקות' },
      { eng: 'REGULARLY', heb: 'באופן קבוע' },
      { eng: 'NEVER', heb: 'אף פעם לא' },
      { eng: 'ALWAYS', heb: 'תמיד' },
      { eng: 'USUALLY', heb: 'בדרך כלל' },
      { eng: 'OFTEN', heb: 'לעיתים קרובות' },
      { eng: 'TWICE', heb: 'פעמיים' },
      { eng: 'TODAY', heb: 'היום' },
      { eng: 'EVERY', heb: 'כל יום / שבוע / שנה' },
      { eng: 'MONDAY', heb: 'בימי שני' },
    ],
  },
  {
    label: 'שבוע 4',
    words: [
      { eng: 'FORGET', heb: 'לשכוח' },
      { eng: 'EVERYONE', heb: 'כולם' },
      { eng: 'FIRST', heb: 'ראשון' },
      { eng: 'SECOND', heb: 'שני' },
      { eng: 'THIRD', heb: 'שלישי' },
      { eng: 'GIVE', heb: 'לתת' },
      { eng: 'HEALTHY', heb: 'בריא' },
      { eng: 'INSTRUCTIONS', heb: 'הוראות' },
      { eng: 'MEAN', heb: 'להתכוון / משמעות' },
      { eng: 'TRY', heb: 'לנסות' },
    ],
  },
  {
    label: 'שבוע 5',
    words: [
      { eng: 'SPECIAL', heb: 'מיוחד' },
      { eng: 'ONCE', heb: 'פעם אחת' },
      { eng: 'ABOUT', heb: 'על / בערך' },
      { eng: 'BECAUSE', heb: 'בגלל / כי' },
      { eng: 'LEARN', heb: 'ללמוד' },
      { eng: 'UNDERSTAND', heb: 'להבין' },
      { eng: 'VISIT', heb: 'לבקר' },
      { eng: 'TONIGHT', heb: 'הלילה' },
      { eng: 'TOMORROW', heb: 'מחר' },
      { eng: 'TODAY', heb: 'היום' },
    ],
  },
  {
    label: 'שבוע 6',
    words: [
      { eng: 'EVERYTHING', heb: 'הכל' },
      { eng: 'PRACTICE', heb: 'לתרגל / אימון' },
      { eng: 'FAMOUS', heb: 'מפורסם' },
      { eng: 'WEEKEND', heb: 'סוף שבוע' },
      { eng: 'HEAR', heb: 'לשמוע' },
      { eng: 'HERE', heb: 'כאן' },
      { eng: 'BELOW', heb: 'למטה / מתחת' },
      { eng: 'ANOTHER', heb: 'אחר / נוסף' },
      { eng: 'ARRIVE', heb: 'להגיע' },
      { eng: 'MORNING', heb: 'ערב טוב / בוקר טוב' },
    ],
  },
  {
    label: 'שבוע 7',
    words: [
      { eng: 'INFORMATION', heb: 'מידע' },
      { eng: 'INTERESTING', heb: 'מעניין' },
      { eng: 'IDEA', heb: 'רעיון' },
      { eng: 'LEAVE', heb: 'לעזוב' },
      { eng: 'MEET', heb: 'לפגוש' },
      { eng: 'MINUTE', heb: 'דקה' },
      { eng: 'HOUR', heb: 'שעה' },
      { eng: 'PLAN', heb: 'תוכנית / לתכנן' },
      { eng: 'STAY', heb: 'להישאר' },
      { eng: 'SPEAK', heb: 'לדבר' },
    ],
  },
  {
    label: 'שבוע 8',
    words: [
      { eng: 'WORRY', heb: 'לדאוג' },
      { eng: 'VACATION', heb: 'חופשה' },
      { eng: 'VISITOR', heb: 'מבקר / אורח' },
      { eng: 'QUESTION', heb: 'שאלה' },
      { eng: 'NOW', heb: 'עכשיו / ממש עכשיו' },
      { eng: 'MOMENT', heb: 'כרגע' },
      { eng: 'PRESENT', heb: 'נכון לעכשיו' },
      { eng: 'WRITE', heb: 'לכתוב' },
      { eng: 'COPY', heb: 'להעתיק' },
      { eng: 'WEEK', heb: 'השנה / החודש / היום / השבוע' },
    ],
  },
];
